<template>
    <div
    class="bg-dark text-light"
    style="height:100vh;">
        <title-header
        :from="from"
        :stats="title_stats"
        :info="title_info">
        </title-header>

        <title-menu></title-menu>

        <zoom-x-transition group :duration="500">
        <!-- <transition-group name="scale-up-hor-center"> -->
            <router-view :key="$route.fullPath"></router-view>
        <!-- </transition-group> -->
        </zoom-x-transition>

        <!-- <router-view v-else :key="$route.fullPath"></router-view> -->
    </div>
</template>

<script>
    import axios from 'axios';
    import header from '@/components/titleInfo/header/header.vue';
    import titleMenu from '@/components/titleInfo/header/menu.vue';
    export default{
        name: 'titleInfo',
        components: {
            'title-header': header,
            'title-menu': titleMenu
        },
        data(){
            return{
                title_info: {},
                title_stats: {},
                from: ''
            }
        },
        beforeRouteUpdate(to, from, next){
            if(to.params.titleid!=from.params.titleid){
                this.$Progress.start();
                let title_info={};
                let title_stats={};
                axios.get("https://api.jikan.moe/v3/"+to.params.type+"/"+to.params.titleid)
                .then(response => {
                    console.log(response.data)
                    let data=response.data;

                    let image=data.image_url.slice(0,-4)+'l.jpg';
                    title_info={
                        id: data.mal_id,
                        image: image,
                        title: data.title
                    };

                    title_stats={
                        score: data.score,
                        members: data.members,
                        favourites: data.favorites,
                        rank: data.rank
                    };
                    this.title_info=title_info;
                    this.title_stats=title_stats;
                    next();
                    this.$Progress.finish();
                }).catch(error => { console.log(error) });
            }
            else next();
        },
        beforeRouteEnter(to, from, next){
            let title_info={};
            let title_stats={};
            
            axios.get("https://api.jikan.moe/v3/"+to.params.type+"/"+to.params.titleid)
            .then(response => {
                console.log(response.data)
                let data=response.data;

                let image=data.image_url.slice(0,-4)+'l.jpg';
                title_info={
                    id: data.mal_id,
                    image: image,
                    title: data.title
                };

                title_stats={
                    score: data.score,
                    members: data.members,
                    favourites: data.favorites,
                    rank: data.rank
                };
                next(vm => {
                    vm.$Progress.start();
                    vm.title_info=title_info;
                    vm.title_stats=title_stats;
                    vm.from=from.fullPath;
                    vm.$Progress.finish();
                });
            }).catch(error => { console.log(error) });
        }
    };
</script>

<style type="text/css">
    .ui-collapsible__body{
        border:0;
        padding:0;
        margin:0;
        text-align: left;
    }

    .scale-up-hor-center-enter-active {
    -webkit-animation: scale-up-hor-center-enter-active 0.3s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
            animation: scale-up-hor-center-enter-active 0.3s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2020-4-23 10:55:46
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-hor-center-enter-active
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-hor-center-enter-active {
  0% {
    -webkit-transform: scaleX(0.4);
            transform: scaleX(0.4);
  }
  100% {
    -webkit-transform: scaleX(1);
            transform: scaleX(1);
  }
}
@keyframes scale-up-hor-center-enter-active {
  0% {
    -webkit-transform: scaleX(0.4);
            transform: scaleX(0.4);
  }
  100% {
    -webkit-transform: scaleX(1);
            transform: scaleX(1);
  }
}

</style>